### ISSUE TITLE
invalid JPEG format: missing 0xff00 sequence

### ISSUE THREAD

**Issue by mrsongindezhou** [disintegration/imaging#103]
Hello author, I have a problem.
An error was reported when the picture was opened

invalid JPEG format: missing 0xff00 sequence

Picture url:https://img.alicdn.com/bao/uploaded/i1/92690615/O1CN01G2rJW31GPi5hNX0gD_!!92690615.jpg

**Comment by mrsongindezhou** [comment]
img1, err := imaging.Open(ip1)

**Comment by disintegration** [comment]
Hello,

I get no error when opening the linked image.

```
package main

import (
	"log"

	"github.com/disintegration/imaging"
)

func main() {
	img, err := imaging.Open("test.jpg")
	if err != nil {
		log.Fatalf("failed to open image: %v", err)
	}
	log.Printf("decoded image size: %dx%d", img.Bounds().Dx(), img.Bounds().Dy())
}
```

```
$ go run main.go 
2019/09/04 22:30:04 decoded image size: 640x640
```

Anyway, the `imaging.Open` function is just a simple wrapper around `image.Decode`, which in turn calls individual image decoding packages depending on the image format (the standard package `image/jpeg` is used for JPEG). Try using the `image/jpeg` package directly. If it fails to decode a valid image, you can try opening an issue in the main go repository (https://github.com/golang/go)
