### ISSUE TITLE
Resize using "fill" method, to add pixels in order to keep aspect ratio

### ISSUE THREAD

**Issue by rogierlommers** [disintegration/imaging#105]
First of all, thanks for your nice library!
Now I have a question: I'm looking for a resize-method which does the following:

- Takes an original image
- The function should accept target x and y
- The function should resize the original to x and y pixels in size, but it should keep the aspect ratio intact. Sometimes it is not possible to do that, therefore we need to add additional pixels.

Please see attached example to get a better idea. the original image was 157 width, by 200 heigh. The "request" target size was approx 200x200. This means that we need to "introduce" some additional pixels on the x-axis, in this case in the color red.

![9GligT5l4dy9zRrtlMkNDU](https://user-images.githubusercontent.com/3907131/68670287-d8224780-054c-11ea-8cf0-a1c1a936aab1.jpg)

Does your package now support this? I found the `Fill(img image.Image, width, height int, anchor Anchor, filter ResampleFilter) *image.NRGBA`-function, but this is not 100% what I need, right? The problem now is that I loose some "original" pixels, due to the fact that there is cropping involved.

**Comment by disintegration** [comment]
There is no special function for this type of image manipulation. But it can be done by pasting the resized image to the new image of the desired size, e.g.:

```go
package main

import (
	"image"
	"image/color"
	"log"

	"github.com/disintegration/imaging"
)

func main() {
	img, err := imaging.Open("src.jpg")
	if err != nil {
		log.Fatal(err)
	}

	img = makeThumbnail(img, 200, 200, color.RGBA{255, 0, 0, 255})

	if err := imaging.Save(img, "dst.jpg"); err != nil {
		log.Fatal(err)
	}
}

func makeThumbnail(img image.Image, w, h int, bgColor color.Color) image.Image {
	return imaging.PasteCenter(
		imaging.New(w, h, bgColor),
		imaging.Fit(img, w, h, imaging.Lanczos),
	)
}
```

src.jpg

![src](https://user-images.githubusercontent.com/2706839/68706010-26146b00-05a0-11ea-9249-2dd4adfc9364.jpg)

dst.jpg

![dst](https://user-images.githubusercontent.com/2706839/68706036-32002d00-05a0-11ea-8beb-93f3e182af58.jpg)

**Comment by rogierlommers** [comment]
Thanks @disintegration , this indeed is exactly what I need.
