### ISSUE TITLE
Can I Change Image DPI ?

### ISSUE THREAD

**Issue by A29sTech** [disintegration/imaging#108]

**Comment by disintegration** [comment]
There's no way to set the DPI using the `imaging` API. The `imaging.Save` and `imaging.Encode` functions use packages from the standard library (e.g. `image/jpeg`) and `golang.org/x/image` subpackages to encode images. These packages don't support saving or retrieving image metadata such as DPI.

**Comment by inliquid** [comment]
There is no such parameter as "DPI" within an image, DPI is evaluated from __resolution__ when it's applied to particular physical dimensions. So exact same image will have different DPI depending on will it be displayed on 5.5" smartphone, 25" monitor or printed on an A4 paper.
