### ISSUE TITLE
README lacks images

### ISSUE THREAD

**Issue by AlekSi** [disintegration/imaging#11]
For example, images for resize, fit and thumbnail. Also, for `ResampleFilter`s.

**Comment by disintegration** [comment]
Added a few image examples.

**Comment by AlekSi** [comment]
It would be nice to have images for Resize, Fit, Thumbnail.

**Comment by disintegration** [comment]
Added a few examples for Resize, Fit and Fill functions. The latter has the same effect as Thumbnail with the exception that it allows to specify an anchor point.
