### ISSUE TITLE
Rotate 16-bit monochrome image data

### ISSUE THREAD

**Issue by brandondube** [disintegration/imaging#110]
Is there a way to use this to rotate 16-bit monochrome images (`image.Gray16`) without quantization  / loss of bit depth?  I know the outputs are all `image.NRGBA`, but maybe I do not understand stdlib image well enough.

**Comment by disintegration** [comment]
No, there is no way to do this using the imaging package. It always outputs a 8bit/channel rgba image.

Some alternatives that may be helpful
- github.com/disintegration/gift
- golang.org/x/image/draw

**Comment by brandondube** [comment]
That's a shame, thanks anyway.
