### ISSUE TITLE
Compress animated gif

### ISSUE THREAD

**Issue by theflyingcodr** [disintegration/imaging#113]
Does this library support animated gif compression? I have tried it with an animated gif and it seemed to strip off all frames except for the first. Is there a setting/config/something I need to implement to make this work or is it just not currently supported?

**Comment by disintegration** [comment]
When dealing with animated gifs you need to use `gif.DecodeAll` and `gif.EncodeAll` functions and process each animation frame separately. See #23 for a basic example, except the line `runtime.GOMAXPROCS(runtime.NumCPU())` - it is not needed anymore.

**Comment by theflyingcodr** [comment]
Perfect thanks I'll give that a go, sorry for the delay, totally missed the notification!
