### ISSUE TITLE
How to crop file same as `imaging.Fit` without quality loss?

### ISSUE THREAD

**Issue by mesuutt** [disintegration/imaging#114]
I want to use `imaging.Fit` without filtering.
When I use `.Fit` image quality falling. 
I want to crop file same as `.Fit` without loss qualty. How can I do this?

**Comment by disintegration** [comment]
> I want to use imaging.Fit without filtering.

To disable filtering use `imaging.NearestNeighbor` as the last parameter of the `imaging.Fit` function.

**Comment by mesuutt** [comment]
Hi @disintegration, thanks for your reply.

I used  `imaging.NearestNeighbor` but image qualty still poor. Maybe this is not related `imaging` but I don't found any issue at code. I want to crop max 640x640 and save.

```go
img, _, err := image.Decode(bytes.NewReader(*fileContentBytes))
if err != nil {
    return err
}

thumbnailImg := imaging.Fit(img, 640, 640, imaging.NearestNeighbor)
f, err := os.Create("foo.jpeg")
if err != nil {
    return err
}

defer f.Close()
buf := new(bytes.Buffer)
if err := jpeg.Encode(buf, thumbnailImg, &jpeg.Options{Quality:100}); err != nil {
    return err
}
_, err = f.Write(*file.Content)
if err != nil {
    return err
}

```
Original Image:
![Belinda   Nan-ccf4df](https://user-images.githubusercontent.com/823338/76898955-bbee3880-68a7-11ea-8253-a569753f7e6c.jpg)

New created image( there are white dots in image):
![belinda-and-nan](https://user-images.githubusercontent.com/823338/76898946-b8f34800-68a7-11ea-9776-e6be75cf7994.jpg)

**Comment by disintegration** [comment]
Are you sure you've attached the right original image? It's already 640 pixels wide so `Fit` does essentially nothing.

Here's the code i've used:
```
package main

import (
	"log"

	"github.com/disintegration/imaging"
)

func main() {
	src, err := imaging.Open("src.jpg")
	if err != nil {
		log.Fatal(err)
	}
	dst := imaging.Fit(src, 640, 640, imaging.NearestNeighbor)
	if err := imaging.Save(dst, "dst.jpg"); err != nil {
		log.Fatal(err)
	}
}
```

And the result:

![dst](https://user-images.githubusercontent.com/2706839/76990878-b8b38500-6959-11ea-94f1-5499a7e5cbb4.jpg)

I believe the original image in your example was larger.

You asked for no-filtering mode, but for this type of image (photography) you won't get a high quality result by disabling filtering, quite the opposite. My recommendation is to use the CatmullRom or Lanczos filter.

**Comment by disintegration** [comment]
Closing the issue. Feel free to reopen if you have any further questions.
