### ISSUE TITLE
gif: can't recognize format "\x89PNG\r\n"

### ISSUE THREAD

**Issue by x0rzkov** [disintegration/imaging#115]
Hi,

Hope you are all well !

When opening some gifs, I have the following error
```bash
gif: can't recognize format "\x89PNG\r\n"
```

Is there a way to fix it or make it work ?

Cheers,
X

**Comment by disintegration** [comment]
Hi,

> "\x89PNG\r\n"

This looks like a PNG image header, not GIF. Are you using the `imaging.Open` function to open the image?

Could you please provide a code example and the image so I can reproduce the issue.

**Comment by disintegration** [comment]
Closing the issue. Feel free to reopen if you have any further questions.
