### ISSUE TITLE
cropping bounding box

### ISSUE THREAD

**Issue by x0rzkov** [disintegration/imaging#116]
Hi,

Hope you are all well !

I am working on a fork of https://github.com/LdDl/go-darknet and I need to crop images inside the bounding box detected.

So, is it possible to crop an image with bounding box parameters with imaging ?

For example:
- https://cdn-photos.autosphere.fr/media/FL/FL-823-GFB.jpg
- car (2): 99.4160% | start point: (42,51) | end point: (772, 485)
- would be like left, top, right-left, bot-top

Thanks in advance for your input and insights on that.

Cheers,
X

**Comment by disintegration** [comment]
Hi,

Is this what you need?

```go
package main

import (
	"image"
	"log"

	"github.com/disintegration/imaging"
)

func main() {
	img, err := imaging.Open("FL-823-GFB.jpg")
	if err != nil {
		log.Fatal(err)
	}

	var (
		x = 42
		y = 51
		w = 772
		h = 485
	)

	img = imaging.Crop(img, image.Rect(x, y, x+w, y+h))

	if err := imaging.Save(img, "result.jpg"); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by x0rzkov** [comment]
yeah, we have implemented that https://github.com/LdDl/go-darknet/blob/master/example/main.go#L84.

Thanks a lot !
