### ISSUE TITLE
draw a rectangle in an image

### ISSUE THREAD

**Issue by x0rzkov** [disintegration/imaging#117]
Hi guys,

Hope you are all well !

Is it possible to draw a rectangle with coordinates in an existing image with imaging ?

like in this example 
![Yolov4](https://miro.medium.com/max/2650/1*ZwmYzbzFeujr4wWCem-bGA.jpeg "Yolov4")

Cheers,
X

**Comment by disintegration** [comment]
Hi,
No, `imaging` package does not provide any line or text drawing functionality.
