### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by ghost** [disintegration/imaging#12]
**Dear Grigory Dryapak**,

This is completely awesome open source code project, But it does't support GIF file.

Can you please provide GIF support for this.

Thank you.

**Comment by ernsheong** [comment]
Is this argument still valid? It is 2019.

**Comment by disintegration** [comment]
@ernsheong The support for GIF format in `Save` function mentioned here was added in 2014 (https://github.com/disintegration/imaging/commit/c317ebdc7ab5aadf50ac72c10bf0ec4515c5a561)
