### ISSUE TITLE
Stream

### ISSUE THREAD

**Issue by nseb** [disintegration/imaging#122]
Hi,
it's possible to open image with Stream , because I want use framework in google function to load image in google storage with google api.

Best Regards

**Comment by disintegration** [comment]
Hi,

Could you please provide more details on the issue? What do you mean by "open image with Stream"?

To load an image data coming from other APIs you can use the `imaging.Decode` function that takes an `io.Reader` as its first argument. If you're working with the Google Cloud Storage, you can use the `NewReader` method of the `ObjectHandle` to get the reader of the object data.
(https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#ObjectHandle.NewReader)

**Comment by jz222** [comment]
Hi,

I'm looking for something similar. I would like to stream an image from one bucket, resize it and stream it into another bucket. [This](https://medium.com/google-cloud/google-cloud-storage-downsizer-af0048591e40) article explains exactly what I'm trying to achieve.

**Comment by disintegration** [comment]
I'm not very familiar with Google Cloud Storage. Looking at the docs, you can do a similar processing in Go:
- Create a new reader of the source image object (https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#ObjectHandle.NewReader)
- Create a new writer to the destination image object in another bucket (https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#ObjectHandle.NewWriter)
- Use `imaging.Decode` function to read the image from the reader.
- Use `imaging.Resize` to resize the image.
- Use `imaging.Encode` to write the resized image to the writer.

**Comment by disintegration** [comment]
Closing the issue. Feel free to reopen if you have any further questions.
