### ISSUE TITLE
PNG compression is invalid

### ISSUE THREAD

**Issue by aveyuan** [disintegration/imaging#127]
Hi, I try Use PNG compression,but The size has not changed.

Code 

```
package main

import (
	"image/png"

	"github.com/disintegration/imaging"
)

func main() {
	img, err := imaging.Open("test.png")
	if err != nil {
		panic(err)
	}

	b := img.Bounds()

	dstImage128 := imaging.Resize(img, b.Dx(), b.Dy(), imaging.Lanczos)

	imaging.Save(dstImage128, "x1.png", imaging.PNGCompressionLevel(png.BestCompression))

}

```

Output pic

![image](https://user-images.githubusercontent.com/10907648/89481620-bea3e880-d7ca-11ea-9988-0ac16ef639ae.png)

I want to compress more, how did I do it? Thanks

**Comment by disintegration** [comment]
Hi,

This package does not implement implement any image encoding methods itself. To encode image to PNG it uses the standard `image/png` package. The given compression level (`png.BestCompression`) is the maximum compression that is available.

**Comment by aveyuan** [comment]
> 你好
> 
> 该程序包本身不实现任何图像编码方法。要将图像编码为PNG，它使用标准`image/png`包。给定的压缩级别（`png.BestCompression`）是可用的最大压缩率。

Thanks
