### ISSUE TITLE
can i translate pic to round pic?

### ISSUE THREAD

**Issue by rhettli** [disintegration/imaging#128]
![image](https://user-images.githubusercontent.com/26317003/91115837-af270980-e6bd-11ea-889e-c31b7de316e7.png)

![image](https://user-images.githubusercontent.com/26317003/91115797-9dddfd00-e6bd-11ea-93ae-c5e6fe8b3454.png)
![image](https://user-images.githubusercontent.com/26317003/91115823-a9312880-e6bd-11ea-86c0-44fc42c9cf43.png)

**Comment by disintegration** [comment]
There is no ready-to-use function to do such thing. See #72 for some examples that may be helpful to you.

**Comment by rhettli** [comment]
@disintegration oh,thanks
