### ISSUE TITLE
How to get binary data instead of writing to filesystem

### ISSUE THREAD

**Issue by squarebrakets** [disintegration/imaging#138]
Hello, I would like to store very small resized images to a DB as binary data. What can I do?

**Comment by disintegration** [comment]
Hello,

You can use the Encode function (imaging.Encode or jpeg.Encode or png.Encode etc) to write the resized image to a bytes.Buffer and store buffer.Bytes() to the database.

**Comment by squarebrakets** [comment]
Thank you
