### ISSUE TITLE
Cannot apply transparency

### ISSUE THREAD

**Issue by rafa-acioly** [disintegration/imaging#148]
I'm trying to crop a image as a circle (https://github.com/disintegration/imaging/issues/72) and apply a `color.Transparent`, but the image is getting a `white` border

```go
func makeCircleSmooth(src image.Image, factor float64) image.Image {
	d := src.Bounds().Dx()
	if src.Bounds().Dy() < d {
		d = src.Bounds().Dy()
	}
	dst := imaging.CropCenter(src, d, d)
	r := float64(d) / 2
	for x := 0; x < d; x++ {
		for y := 0; y < d; y++ {
			xf := float64(x)
			yf := float64(y)
			delta := math.Sqrt((xf-r)*(xf-r)+(yf-r)*(yf-r)) + factor - r
			switch {
			case delta > factor:
				dst.Set(x, y, color.Transparent)
			case delta > 0:
				m := 1 - delta/factor
				c := dst.NRGBAAt(x, y)
				c.A = uint8(float64(c.A) * m)
				dst.Set(x, y, c)
			}
		}
	}
	return dst
}
```

The background (PNG)
![colorful](https://user-images.githubusercontent.com/11068059/132959558-84966307-11b9-4e50-8eba-93cc52df805c.png)

The final result:
![final](https://user-images.githubusercontent.com/11068059/132959554-b935f4dc-d155-4eb0-b3e4-fe80bf5fbc40.png)

I've tried with different pictures and I still got the same result

**Comment by alhamsya** [comment]
@rafa-acioly  how do you solve this issue ?
