### ISSUE TITLE
imaging.Open throw error: image: unknown format

### ISSUE THREAD

**Issue by leoboboyan** [disintegration/imaging#149]
Hi

Thanks for your time.
My code works fine with most images, but only one image throw an error for now.
When opening this image, it throws: image: unknown format
![o](https://user-images.githubusercontent.com/21359568/133880698-15a934ec-6efd-4113-83f1-245a034d7e5a.jpg)
.

**Comment by disintegration** [comment]
Hi,

Looks like it's a WEBP image, not JPEG:

```
$ file 133880698-15a934ec-6efd-4113-83f1-245a034d7e5a.jpg
133880698-15a934ec-6efd-4113-83f1-245a034d7e5a.jpg: RIFF (little-endian) data, Web/P image, VP8 encoding, 500x499, Scaling: [none]x[none], YUV color, decoders should clamp
```

Try adding the following import to enable webp decoder:

```
import _ "golang.org/x/image/webp"
```

Docs: https://pkg.go.dev/golang.org/x/image/webp

**Comment by leoboboyan** [comment]
> Hi,
> 
> Looks like it's a WEBP image, not JPEG:
> 
> ```
> $ file 133880698-15a934ec-6efd-4113-83f1-245a034d7e5a.jpg
> 133880698-15a934ec-6efd-4113-83f1-245a034d7e5a.jpg: RIFF (little-endian) data, Web/P image, VP8 encoding, 500x499, Scaling: [none]x[none], YUV color, decoders should clamp
> ```
> 
> Try adding the following import to enable webp decoder:
> 
> ```
> import _ "golang.org/x/image/webp"
> ```
> 
> Docs: https://pkg.go.dev/golang.org/x/image/webp

thanks
