### ISSUE TITLE
width or heigth == 0 for imaging.Thumbnail

### ISSUE THREAD

**Issue by yml** [disintegration/imaging#20]
I started to play with `imaging` and I very soon stumble on an interesting edge case. `imaging.Resize` handle the case where width or heigth == 0 in a very intuitive way. There is a [check in the code](https://github.com/disintegration/imaging/blob/d13e2be960350b54d0c06cd05e1aa020d2aff0c9/resize.go#L38-L45) to do the right thing but in `imaging.Thumbnail` this case is not supported. I can see argument either way so I am wondering if you this this has a bug or a feature.

**Comment by Tom29** [comment]
@yml can you share your code? I think setting thumbnail width or height = 0 is necessary

**Comment by inliquid** [comment]
I was surprised by this behavior that differs from `Resize`, and I also think `Crop`/`Thumbnail`/`Fit` should respect zero width/height arguments.

**Comment by nf-brentsaner** [comment]
Necrobumping but not reopening, since this repo's dead anyways,

if anyone gets here wondering how to do this/wanting to do this, you can autoscale it yourself and pass the explicit width/height to `Crop()` / `Fit()` / `Fill()` / `Thumbnail()` etc.

Sure, it's boilerplate-y, but it's very much do-able and quite easy.

For example, say you have a source `image.Image` named `img` of `1024x768`(XGA/4:3 aspect ratio) and want to `Crop()` it to a width of `800` pixels.

```go
import (
	"image"

	"github.com/disintegration/imaging"
)

// The current width and height.
var origW int = img.Bounds().Dx()
var origH int = img.Bounds().Dy()

/*
	scaleFactor is the aspect ratio represented by a single number.
	Since 1024x768 is a 4:3 aspect ratio, doing 4/3 will get you the same value as the below.
*/
var scaleFactor float64 = float64(origW) / float64(origH)

// The target width (known).
var tgtW int = 800
// A declared zero-value variable for the target height.
var tgtH int

// Calculating tgtH is as easy as just...
tgtH = tgtW / scaleFactor
// If you had tgtH already and wanted tgtW instead, it'd be:
//tgtW = tgtH * scaleFactor

// And you can now crop accordingly, maintaining aspect ratio,
// while originally only having one of the target dimensions.
var croppedImg image.Image
var croppedSz image.Rectangle = image.Rectangle{
	Min: image.Point{
		X: 0,
		Y: 0,
	},
	Max: image.Point{
		X: tgtW,
		Y: tgtH,
	},
}

croppedImg = imaging.Crop(img, croppedSz)
// Or directly via the convenience function/anchored crop:
croppedImg = imaging.CropAnchor(img, tgtW, tgtH, imaging.Center)
// Or the convenience function for the above, even.
croppedImg = imaging.CropCenter(img, tgtW, tgtH)
```

You can also get the aspect ratio -- `4:3` in our above example -- itself.

```go
import (
	"math"
)

// gcd will hold the Euclidean "Greatest Common Denominator";
// essentially the same as `scaleFactor` above.
var gcd int
var origW int = img.Bounds().Dx()
var origH int = img.Bounds().Dy()

// These are kept as separate variables to avoid touching origW/origH as these'll be modified.
// They're also float64s to avoid doing looped type conversions.
var gcdA float64 = float64(origW)
var gcdB float64 = float64(origH)

// Calculate the GCD.
for gcdB != 0 {
	gcdA, gcdB = gcdB, math.Mod(gcdA, gcdB)
}
gcd = gcdA

// The "4" in "4:3":
// int(float64(origW) / gcd)
// The "3" in "4:3":
// int(float64(origH) / gcd)
```
