### ISSUE TITLE
webp image support

### ISSUE THREAD

**Issue by kodabb** [disintegration/imaging#25]
Hi,
I wanted to contribute webp encoding/decoding to imaging (very nice library btw)!
However I think webp support was introduced around 1.2 and I seem to have read that you'd rather preserve compatibility with older go versions.

Should I rather write webp support in my own application?

**Comment by disintegration** [comment]
Hi,
Thanks!
I thought of adding webp support via `golang.org/x/image/webp` package (pure Go, supported by the Go team). But it seems it implements only the decoder and not the encoder by now.
What package would you suggest?
Go 1.2 requirement is OK, it's already required for GIF encoding.

**Comment by kodabb** [comment]
I only found http://godoc.org/github.com/chai2010/gopkg/image/webp for webp encoding

**Comment by disintegration** [comment]
Yes, I've found it too, but it depends on the C library.
I think it will be better to use it in your application to load and save images, and use `imaging` for image manipulation.
