### ISSUE TITLE
RGB color mixing should be done in a linear gamma color space

### ISSUE THREAD

**Issue by pftbest** [disintegration/imaging#26]
for example try to scale this image down by 50%:
![image](http://www.4p8.com/eric.brasseur/gamma_dalai_lama_gray.jpg)
this library will give incorrect result:
![icorrect](https://googledrive.com/host/0B4ouTzM6vLORflJYVGZHUzk2VTZpRW1KUzh5VEhOWXNGVlBlbjBRYlZzcEJBTzNkWFpneVE/2.png)
scaling performed by a correct software:
![correct](http://www.4p8.com/eric.brasseur/gamma_dalai_lama_gray_good.jpg)

more info on the subject can be found in this [article](http://www.4p8.com/eric.brasseur/gamma.html)
there is also a nice video on youtube: https://youtu.be/LKnqECcg6Gw

**Comment by disintegration** [comment]
Hi,

You're right. I'm aware of the colorspace issue. Adding a colorspace conversions into every processing function will drop the performance considerably, especially if you have several processing steps. I think it's better to do what the article suggests manually. With `imaging` you can apply a gamma correction before and after the image processing:

```go
dst := imaging.AdjustGamma(src, 1/2.2)
dst = imaging.Resize(dst , src.Bounds().Dx()/2, src.Bounds().Dy()/2, imaging.Lanczos)
dst = imaging.AdjustGamma(dst, 2.2)
```

Please also take a look at the another package I created, that aims at the higher quality image processing: `github.com/disintegration/gift`. I've implemented special filters that use the right formula to convert the colorspace to linear and back. It also allows to use 16bit per channel images as a target. The respective example:

```go
g := gift.New(
		gift.ColorspaceSRGBToLinear(),
		gift.Resize(src.Bounds().Dx()/2, src.Bounds().Dy()/2, gift.LanczosResampling),
		gift.ColorspaceLinearToSRGB(),
)
dst := image.NewRGBA64(g.Bounds(src.Bounds()))
g.Draw(dst, src)
```

**Comment by pftbest** [comment]
Thanks for reply!
I understand that adding conversions into every step will incur a huge performance penalty, but the fact is it is not even possible to do it right with the current implementation.
The problem is that imaging library works on `NRGBA` images only, but linear RGB values require *at least* 16bit color depth.

small example:
```go
dst := imaging.AdjustGamma(src, 1/2.2)
dst = imaging.AdjustGamma(dst, 2.2)
```
Original image | Filtered image
--- | ---
![original](https://googledrive.com/host/0B4ouTzM6vLORflJYVGZHUzk2VTZpRW1KUzh5VEhOWXNGVlBlbjBRYlZzcEJBTzNkWFpneVE/b1.jpg) | ![filtered](https://googledrive.com/host/0B4ouTzM6vLORflJYVGZHUzk2VTZpRW1KUzh5VEhOWXNGVlBlbjBRYlZzcEJBTzNkWFpneVE/b2.png)

gift library on the other hand uses proper `NRGBA64` temp images in between filter steps, so this code:
```go
g := gift.New(
        gift.ColorspaceSRGBToLinear(),
        // some filtering...
        gift.ColorspaceLinearToSRGB(),
)
dst := image.NewRGBA(g.Bounds(src.Bounds()))
g.Draw(dst, src)
```
will work fine. and there is no need for destination image to be `NRGBA64` because it is back to sRGB space after the `ColorspaceLinearToSRGB` step.

So at the end my suggestion is to add this information in README file, to make users aware of the issue and let them know how to deal with it.

P.S. Sorry for my bad english.

**Comment by disintegration** [comment]
Yes, my AdjustGamma example was actually not very good. While it fixes the issue, the conversion can be quite lossy for 8-bit images. It's the limitation of this package. That's why I suggest to use `gift` if you need more quality. And it's one of the reasons why I even created `gift` and these sRGB<->Linear filters.

I think the difference between linear and sRGB resizing isn't critical for a lot of applications and it's the reason why lots of image libraries and editors don't implement this conversion. For these applications `imaging` works good enough. Maybe it's a good idea to write about it in the README, because sometimes people ask me what's the difference between these two packages. I'll think about it.
