### ISSUE TITLE
Selecting * image.YCbCr instead * image.NRGBA

### ISSUE THREAD

**Issue by mantyr** [disintegration/imaging#28]
You use *image.NRGBA the default, but the standard library saves the image in *image.YCbCr. As a result, at least one extra converting image.

I plan to rewrite on the *image.YCbCr, but not anytime soon.

I noticed when working with jpeg, other formats are not looking.

**Comment by disintegration** [comment]
Standard library uses different image types (RGBA, NRGBA, YCbCr). Imaging library functions accept any input image type but always return *image.NRGBA for consistency, so it's easier to convert the image first and use the direct pixels access during image manipulation.

**Comment by mantyr** [comment]
With *image.YCbCr would not be able to use all the same? As an internal format you can use anything, if the standard library saves *image.YCbCr then why not use it.

**Comment by disintegration** [comment]
Standard library only uses *image.YCbCr for JPEG images (not for all of them though). It uses *image.NRGBA or NRGBA64 for PNGs, *image.Paletted for GIFs. But RGBA color model is easier to work with.

**Comment by mantyr** [comment]
Ok.
