### ISSUE TITLE
Image Rotated after blur

### ISSUE THREAD

**Issue by daemonfire300** [disintegration/imaging#30]
Hi there,

Images (JPEG) get rotated by 90 degree if blured.
```
func blurImage(src io.Reader, imgType string) ([]byte, error) {
	/*switch imgType {
	case "jpeg":
		img, err = jpeg.Decode(src)
	case "png":
		img, err = png.Decode(src)
	case "gif":
		img, err = gif.Decode(src)
	default:
		return nil, errors.New("No filetype")
	}*/
	img, imgType, err := image.Decode(src)
	if err != nil {
		return nil, err
	}
	var blurSigma float64
	confBlurSigmaStr := os.Getenv("Blur_Sigma")
	if confBlurSigmaStr == "" {
		blurSigma = 25
	} else {
		blurSigma, err = strconv.ParseFloat(confBlurSigmaStr, 64)
	}
	if err != nil {
		return nil, err
	}
	bluredImg := imaging.Blur(img, blurSigma)
	return encodeImage(bluredImg, imgType)
}
```

**Comment by disintegration** [comment]
Hi,

Probably your jpeg image contains an orientation exif tag that rotates the image. After you load and save the image, the orientation tag is gone. Exif loading/saving is not supported by Go image package.

You can test it with simpler code. Take the same image and load it with `jpeg.Decode` then save it with `jpeg.Encode`. See if the result is rotated.

**Comment by daemonfire300** [comment]
@disintegration I think it's the problem you described. But what can I do to fix this? I just stumbled upon this https://github.com/golang/go/issues/12202

**Comment by disintegration** [comment]
The possible solution is to read the orientation exif tag and transform the image accordingly before processing. I've found the example in this repository:

https://github.com/wujiang/image-api

1. Read the orientation tag using the goexif package:

  https://github.com/wujiang/image-api/blob/657e5c8578f7a556c7dcf5a456352ffff1ea6b07/handlers.go#L63

2. Transform the image before doing any processing:

  https://github.com/wujiang/image-api/blob/657e5c8578f7a556c7dcf5a456352ffff1ea6b07/image.go#L43

I didn't test this code so I don't know if it will work for you.

The other solution is to find the Go package that can write the exif metadata, so you can save the original orientaton tag into the new JPEG file.

**Comment by disintegration** [comment]
I'm closing it because it's not the issue of this package. Please let me know if you have any questions.
