### ISSUE TITLE
Some problem in Thumbnail function.

### ISSUE THREAD

**Issue by applee** [disintegration/imaging#32]
There is a premise that we must ensure the integrity of image, so I think there is some problem in Thumbnail function that the if condition is reverse.
```
	if srcAspectRatio > thumbAspectRatio {
		tmp = Resize(img, 0, thumbH, filter)
	} else {
		tmp = Resize(img, thumbW, 0, filter)
	}
```

**Comment by disintegration** [comment]
Hello,
Can you please provide an image and a code example demonstrating the issue? I can't see what's the problem with this code.

**Comment by applee** [comment]
I mean the condition need reverse.
``
if srcAspectRatio < thumbAspectRatio {
``

**Comment by disintegration** [comment]
No, the `Thumbnail` works as intended. It resizes and crops an image to fill the rectangular area.
Probably you should use another function - `Fit`. It resizes an image to fit the given dimensions.

**Comment by applee** [comment]
I'm sorry, you are right, ``Fit`` fits me.
