### ISSUE TITLE
Build failed: effects.go:8: gaussianBlurKernel redeclared in this block

### ISSUE THREAD

**Issue by pva** [disintegration/imaging#37]
Trying to build our service with current git of imaging library and I have following error:

# github.com/disintegration/imaging
../../github.com/disintegration/imaging/effects.go:8: gaussianBlurKernel redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/blur.go:8
../../github.com/disintegration/imaging/effects.go:19: Blur redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/blur.go:26
../../github.com/disintegration/imaging/effects.go:40: blurHorizontal redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/blur.go:47
../../github.com/disintegration/imaging/effects.go:94: blurVertical redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/blur.go:101
../../github.com/disintegration/imaging/resize.go:65: Resize redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/resample.go:19
../../github.com/disintegration/imaging/resize.go:116: resizeHorizontal redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/resample.go:69
../../github.com/disintegration/imaging/resize.go:152: resizeVertical redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/resample.go:137
../../github.com/disintegration/imaging/resize.go:191: resizeNearest redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/resample.go:206
../../github.com/disintegration/imaging/resize.go:236: Fit redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/resample.go:251
../../github.com/disintegration/imaging/resize.go:280: Thumbnail redeclared in this block
	previous declaration at ../../github.com/disintegration/imaging/resample.go:295
../../github.com/disintegration/imaging/resize.go:280: too many errors

Checkout out 3ab6ec5 revision of this library and it works.

**Comment by disintegration** [comment]
I think something's wrong with your `imaging` installation. There is no files named "resample.go" or "blur.go" now. Please try to remove and reinstall the package.

**Comment by pva** [comment]
Yup, I found problem in our build system. Sorry.
