### ISSUE TITLE
Fit fill and Background?

### ISSUE THREAD

**Issue by schmitch** [disintegration/imaging#38]
Hello is there something like: https://github.com/sksamuel/scrimage/blob/master/guide/fit.md
Where you fit the image to something like 100px x 100px and and add a background if it can't fit 100 x 100 correctly? (even transparent backgrounds are supported by that library)

**Comment by disintegration** [comment]
Hello,

There is no special function with such behaviour in the imaging package, but you can make it easily:

```go
func bgFit(src image.Image, w, h int, bgColor color.Color) image.Image {
	dst := imaging.New(w, h, bgColor)
	tmp := imaging.Fit(src, w, h, imaging.CatmullRom)
	return imaging.PasteCenter(dst, tmp)
}
```
I think this function does what you want. Here I create a new image filled with the background color and paste the resized source image into the center of it.

Complete code example:

```go
package main

import (
	"github.com/disintegration/imaging"
	"image"
	"image/color"
)

func main() {
	src, err := imaging.Open("test.png")
	if err != nil {
		panic(err)
	}

	testRed := bgFit(src, 300, 100, color.RGBA{255, 0, 0, 255})
	err = imaging.Save(testRed, "test-red.png")
	if err != nil {
		panic(err)
	}

	testTransparent := bgFit(src, 300, 100, color.Transparent)
	err = imaging.Save(testTransparent, "test-transparent.png")
	if err != nil {
		panic(err)
	}
}

func bgFit(src image.Image, w, h int, bgColor color.Color) image.Image {
	dst := imaging.New(w, h, bgColor)
	tmp := imaging.Fit(src, w, h, imaging.CatmullRom)
	return imaging.PasteCenter(dst, tmp)
}
```

And the result. Red:
![test-red](https://cloud.githubusercontent.com/assets/2706839/12894890/a476a94e-ceaa-11e5-917d-55ff7d1d1fe8.png)

Transparent:
![test-transparent](https://cloud.githubusercontent.com/assets/2706839/12894895/abd835a4-ceaa-11e5-8739-b6e05d734038.png)

**Comment by schmitch** [comment]
Wow thanks, I close this for now okai?
And really thanks for your code.
