### ISSUE TITLE
How to add a watermark?

### ISSUE THREAD

**Issue by skyleelove** [disintegration/imaging#41]
Hi,

 How can i add a watermark to a image?

**Comment by disintegration** [comment]
Hi, 

If you have a transparent watermark image, use either `imaging.Overlay` or `imaging.OverlayCenter`function to place it over other images, e.g.

```go
finalImage := imaging.OverlayCenter(baseImage, watermarkImage, 0.5)
```

In the example above you can manipulate the opacity of the watermark image using the third parameter.

**Comment by skyleelove** [comment]
Hi,
   How to change the watermark's location ?

**Comment by disintegration** [comment]
For example:
```go
finalImage := imaging.Overlay(baseImage, watermarkImage, image.Pt(50, 50), 0.5)
```
In the example above `image.Pt(50, 50)` is the position (x, y) of the watermark image.

**Comment by disintegration** [comment]
Closing it now. Feel free to comment/reopen if you have any further questions.
