### ISSUE TITLE
Strip alpha functionality

### ISSUE THREAD

**Issue by PepijnK** [disintegration/imaging#44]
Hi,

It would be neat to have a strip-alpha-functionality as an option for saving the image. Currently, PNG's that contains an alpha background and are saved to JPG are having a black background.

thanks,
pepijn

**Comment by disintegration** [comment]
Hi, 

You can use `imaging.Overlay` to paste your image over a white background before saving to jpeg:

```go
package main

import (
	"image"
	"image/color"
	"log"

	"github.com/disintegration/imaging"
)

func main() {
	src, err := imaging.Open("src.png")
	if err != nil {
		log.Fatal(err)
	}

	dst := imaging.New(src.Bounds().Dx(), src.Bounds().Dy(), color.White)
	dst = imaging.Overlay(dst, src, image.Pt(0, 0), 1.0)

	err = imaging.Save(dst, "dst.jpg")
	if err != nil {
		log.Fatal(err)
	}
}
```
src.png:

![src](https://cloud.githubusercontent.com/assets/2706839/19901945/f7d23af8-a079-11e6-888f-650ce0a4d722.png)

dst.jpg:

![dst](https://cloud.githubusercontent.com/assets/2706839/19901947/ff89da26-a079-11e6-943f-549a8b3336c3.jpg)

**Comment by disintegration** [comment]
To sum up, I think the additional option is not needed here. The `Overlay` function allows to change the background color to any color (not just white) before saving.

I'm closing the issue. Feel free to comment/reopen if you have any further questions.
