### ISSUE TITLE
image White and black

### ISSUE THREAD

**Issue by al3duc** [disintegration/imaging#45]
as converting a binary image in color? White and black?

**Comment by disintegration** [comment]
Hello,
Could you please provide more details on the issue? I'm not sure I understand what you mean.

**Comment by disintegration** [comment]
Closing this issue. Feel free to reopen if necessary.

**Comment by benyu** [comment]
imaging.New(100,100, color.RGBA{224,240,237,1})
Maybe means that It will create a black image (whatever rgb value)!

**Comment by disintegration** [comment]
Hello,

In your example `color.RGBA{224,240,237,1}` is a bad color representation. Alpha channel = 1, but for alpha-premultiplied color it cannot be less than r g b values. Probably you meant `color.RGBA{224,240,237,255}`.

**Comment by benyu** [comment]
Thanks, that's right!

**Comment by benyu** [comment]
Thanks @disintegration
