### ISSUE TITLE
Gray edges on transparent png resizes

### ISSUE THREAD

**Issue by EvanPurkhiser** [disintegration/imaging#46]
Hey, using the following code:

```go
package main

import (
    "log"

   "github.com/disintegration/imaging"
)

func main() {
    src, err := imaging.Open("src.png")
    if err != nil {
        log.Fatal(err)
    }

    dst := imaging.Resize(src, 200, 200, imaging.Lanczos)

    err = imaging.Save(dst, "dst.png")
    if err != nil {
        log.Fatal(err)
    }
}
```

I'm seeing gray aliasing on the resized image:

Example:

Original:
![image](https://cloud.githubusercontent.com/assets/1421724/20550401/270eca18-b0ea-11e6-8187-012f890a7dc2.png)

Resized:
![dst](https://cloud.githubusercontent.com/assets/1421724/20550449/87472376-b0ea-11e6-97e7-cf5095246db3.png)

Any ideas what I could do to reduce the gray edge?

**Comment by disintegration** [comment]
Hello,

Thank you for the report and the example! It's a bug, I will look into it. Probably this weekend.

**Comment by disintegration** [comment]
It should be fixed now. Please try to run your code again after updating the package.
Let me know if it didn't work for you.

**Comment by EvanPurkhiser** [comment]
Looks good thank you!
