### ISSUE TITLE
Support for TIF compression 4

### ISSUE THREAD

**Issue by sanbornm** [disintegration/imaging#50]
Would it be possible to get support for TIF compression 4:

`tiff: unsupported feature: compression value 4`

**Comment by disintegration** [comment]
Hello,

This package only implements image processing functions. To decode/encode TIFF images the `golang.org/x/image/tiff` package is used. (the repository is here: https://github.com/golang/image/tree/master/tiff). Looks like this type of compression is not supported by it yet. 

Probably you should open an issue in the main repository of go project instead. https://github.com/golang/go/issues

**Comment by sanbornm** [comment]
Thanks, I'll open an issue there.
