### ISSUE TITLE
Custom anchor based on coordinates

### ISSUE THREAD

**Issue by Ganitzsh** [disintegration/imaging#51]
I can't seem to find a way to specify a custom `Anchor` based on coordinates when cropping an image. What am I missing?

**Comment by disintegration** [comment]
You can use the `Crop` function for that. It allows to specify custom cropping coordinates via the `rect` argument (`image.Rectangle` type).

https://godoc.org/github.com/disintegration/imaging#Crop

**Comment by Ganitzsh** [comment]
Thanks! My bad, I totally missed the `Crop` function.
