### ISSUE TITLE
Unsharp Mask

### ISSUE THREAD

**Issue by amazingfly** [disintegration/imaging#52]
I have been using your code for image resizing mainly, and I would like to apply a unsharp mask.  I feel like this may be possible with the tools you have created, but it is unclear to me.  Can you explain how to do this, or add a function to do so?

Either way thanks for the code!

**Comment by disintegration** [comment]
Hello,

It depends on your use case. You may consider using the `Sharpen` function. It uses the unsharp mask algorithm internally, but it doesn't support the `threshold` and `amount` parameters.

If you need more control on the parameters, you may use the `Blur` function to create a blurred copy of your image and then calculate a value for each pixel according to the formula `Sharpened = Original + ( Original - Blurred ) * Amount`.

The wikipedia article: https://en.wikipedia.org/wiki/Unsharp_masking

See also the `github.com/disintegration/gift` package for more complete implementation of the unsharp mask filter: https://godoc.org/github.com/disintegration/gift#UnsharpMask

**Comment by amazingfly** [comment]
Thank you very much.  I actually already started using gift, its a nice gift thank you :)
