### ISSUE TITLE
Set jpeg quality from 0 to 100

### ISSUE THREAD

**Issue by speedwheel** [disintegration/imaging#54]
Is there any way to set the jpeg quality from 0 to 100?

**Comment by disintegration** [comment]
Hello,

You can set the quality using `jpeg.Encode` function directly, e.g.:
```
err := jpeg.Encode(w, img, &jpeg.Options{Quality: 70})
```
See http://godoc.org/image/jpeg#Encode

As for `imaging.Save` function, it doesn't support any additional options.
