### ISSUE TITLE
problem with resizing animated gif

### ISSUE THREAD

**Issue by shen-xianpeng** [disintegration/imaging#55]
after resizing,   original animated gif has no animation, how to output an animated gif image

**Comment by disintegration** [comment]
When dealing with animated gifs you need to use `gif.DecodeAll` and `gif.EncodeAll` functions and process each animation frame separately. See https://github.com/disintegration/imaging/issues/23 for a basic example, except the line `runtime.GOMAXPROCS(runtime.NumCPU())` - it is not needed anymore.

**Comment by shen-xianpeng** [comment]
Thank you very much!
