### ISSUE TITLE
how can I crop the desired size

### ISSUE THREAD

**Issue by am4ne** [disintegration/imaging#56]
I want to cut the Image(480×853) to (720 × 370).
so, I run

```
a := image.Rect(0,0,720,370)
src, _ := imaging.Open("FILE.jpg")
dst := imaging.Resize(src, 720, 0, imaging.Lanczos) 
dst = imaging.Crop(src, a)
imaging.Save(dst, "dst.jpg")
```

but result is (480 × 370)
how can I cut the image to (720 × 370)

**Comment by disintegration** [comment]
In your code example you're cropping the original image instead of the resized one.
```
dst = imaging.Crop(src, a)
```
Try replacing this line with
```
dst = imaging.Crop(dst, a)
```

**Comment by am4ne** [comment]
wow...
Sorry for that I came out with sucha silly question.
Thank you;)
