### ISSUE TITLE
Paste image got a wrong result

### ISSUE THREAD

**Issue by yusank** [disintegration/imaging#57]
``` go
result := imaging.Paste(bm, dst, image.Pt(20, 40))
```

when i try to paste `dst` onto `bm`，I got an image like this

![1234](https://user-images.githubusercontent.com/21994267/29749341-9e44850e-8b5b-11e7-85a8-1e9ce0a3a76d.jpg)

**Comment by yusank** [comment]
Here is  `dst`

![target](https://user-images.githubusercontent.com/21994267/29749358-00ff340a-8b5c-11e7-9a40-74226fe6f8e7.png)

**Comment by disintegration** [comment]
The `dst` image is a partially-transparent PNG. If you save it as JPEG, all the transparent areas become black. So the provided result is expected.

Depending of what you're trying to achieve, try one of these options:
1. Save the result image as a PNG.
2. Use `Overlay` instead of `Paste`, e.g.: 
```go
result := imaging.Overlay(bm, dst, image.Pt(20, 40), 1)
```

**Comment by yusank** [comment]
ok, I try the `Overlay` and it works, thanks a lot .

![1234](https://user-images.githubusercontent.com/21994267/29756063-22ab4518-8bd3-11e7-995a-e2e239275156.jpg)
