### ISSUE TITLE
Rotate with offset/anchor/origin

### ISSUE THREAD

**Issue by anihex** [disintegration/imaging#61]
Hi,

is it possible to add a function for rotating an image and specify the offset ourself? I've checked the code and it seems the function for this is already there ... Just private ...
This would be a great help.

**Comment by disintegration** [comment]
Hi,
What do you mean by "offset". Could you provide an example?

**Comment by anihex** [comment]
Hi,

yesterday I was too tired to provide an example. And when I thought about it, it seems not everyone uses the same name for what I meant. Some call it offset, other call it origin and some call it anchor.
I'll call it anchor from now on.

Here is the example:
![image](https://anihex.de/rotate45.png)

Left-Top: No rotation
Right-Top: 45°, anchor at 200,200
Left-Bottom: 45°, anchor at 200, 360
Right-Bottom: 45°, anchor at 200, 40

**Comment by disintegration** [comment]
Thank you for the example. 

The current behavior of `Rotate` is to adjust the size of the destination image to fit the entire rotated source image. So changing the anchor point won't change the result.

If i understand you correctly, what you need is: the size of the destination image to stay the same as the original and to crop the parts of the image that are out of these bounds after the rotation. Is that correct?

For example, given the original image:
![test](https://user-images.githubusercontent.com/2706839/34603363-b5114860-f214-11e7-9ba0-7ec2e846cbae.png)

Resulting images after rotation 30 and 60 degrees clockwise with the anchor point (20,20):

![rotated-030](https://user-images.githubusercontent.com/2706839/34604039-7a46786a-f217-11e7-8c9e-5c70092c8fbf.png) ![rotated-060](https://user-images.githubusercontent.com/2706839/34604042-7dee358e-f217-11e7-84b4-cf14966d0a52.png)

Here's the example code using `golang.org/x/image/draw` and the affine transformation matrix:

```
package main

import (
	"fmt"
	"image"
	"log"
	"math"

	"github.com/disintegration/imaging"
	"golang.org/x/image/draw"
	"golang.org/x/image/math/f64"
)

func main() {
	src, err := imaging.Open("test.png")
	if err != nil {
		log.Fatal(err)
	}
	for a := float64(0); a < 360; a += 10 {
		dst := rotateAround(src, a, 20, 20)
		err := imaging.Save(dst, fmt.Sprintf("rotated-%03d.png", int(a)))
		if err != nil {
			log.Fatal(err)
		}
	}
}

func rotateAround(src image.Image, angle float64, x, y int) image.Image {
	a := math.Pi * angle / 180
	xf, yf := float64(x), float64(y)
	sin := math.Sin(a)
	cos := math.Cos(a)
	matrix := f64.Aff3{
		cos, -sin, xf - xf*cos + yf*sin,
		sin, cos, yf - xf*sin - yf*cos,
	}
	dst := image.NewRGBA(src.Bounds())
	draw.BiLinear.Transform(dst, matrix, src, src.Bounds(), draw.Src, nil)
	return dst
}
```

**Comment by anihex** [comment]
Hi and thank you for the code. This REALY helps me out.

But I actually don't need to crop the image after rotating. I'd rather have the size adjusted to fit the entire picture. This can be seen using Natron.

I only added crop so I can show a more "compact" example.

**Comment by disintegration** [comment]
The resulting images returned by the `imaging` functions always have min point at (0, 0). Given that we adjust the size of the resulting image to fit the entire image, changing the anchor point won't change the result.

Probably the `golang.org/x/image/draw` will be a better fit for your use case. Using the affine transformation matrix you can rotate the image around any point and calculate the new bounds after the rotation. Rotation by the same angle around different points will result in the same images but with different bounds.

I've adjusted the example code. It prints out the bounds on each iteration.

```
package main

import (
	"fmt"
	"image"
	"log"
	"math"

	"github.com/disintegration/imaging"
	"golang.org/x/image/draw"
	"golang.org/x/image/math/f64"
)

func main() {
	src, err := imaging.Open("test.png")
	if err != nil {
		log.Fatal(err)
	}
	for a := float64(0); a < 360; a += 10 {
		dst := rotateAround(src, a, 20, 20)
		fmt.Printf("angle=%03.0f, bounds=%v\n", a, dst.Bounds())
		err := imaging.Save(dst, fmt.Sprintf("rotated-%03.0f.png", a))
		if err != nil {
			log.Fatal(err)
		}
	}
}

func rotateAround(src image.Image, angle float64, x, y int) image.Image {
	xf, yf := float64(x), float64(y)
	sin, cos := math.Sincos(math.Pi * angle / 180)
	aff := f64.Aff3{
		cos, -sin, xf - xf*cos + yf*sin,
		sin, cos, yf - xf*sin - yf*cos,
	}
	dst := image.NewRGBA(calcBounds(aff, src.Bounds()))
	draw.CatmullRom.Transform(dst, aff, src, src.Bounds(), draw.Src, nil)
	return dst
}

func calcBounds(aff f64.Aff3, b image.Rectangle) image.Rectangle {
	points := [...]image.Point{
		{b.Min.X, b.Min.Y},
		{b.Max.X - 1, b.Min.Y},
		{b.Min.X, b.Max.Y - 1},
		{b.Max.X - 1, b.Max.Y - 1},
	}
	var min, max image.Point
	for i, p := range points {
		x0 := float64(p.X) + 0.5
		y0 := float64(p.Y) + 0.5
		x := aff[0]*x0 + aff[1]*y0 + aff[2]
		y := aff[3]*x0 + aff[4]*y0 + aff[5]
		pmin := image.Point{int(math.Floor(x)), int(math.Floor(y))}
		pmax := image.Point{int(math.Ceil(x)), int(math.Ceil(y))}
		if i == 0 {
			min = pmin
			max = pmax
			continue
		}
		if min.X > pmin.X {
			min.X = pmin.X
		}
		if min.Y > pmin.Y {
			min.Y = pmin.Y
		}
		if max.X < pmax.X {
			max.X = pmax.X
		}
		if max.Y < pmax.Y {
			max.Y = pmax.Y
		}

	}
	return image.Rectangle{Min: min, Max: max}
}
```

**Comment by disintegration** [comment]
I'm closing the issue for now. Feel free to comment/reopen if you have any further questions.
