### ISSUE TITLE
image brightness lost after resize

### ISSUE THREAD

**Issue by kiwionly** [disintegration/imaging#67]
Hi, 

I notice that is image brightness(or sort of ) lost when resize, any idea to fix it ?

**Comment by kiwionly** [comment]
Just realized is causing by the golang image/jpeg package, seem like it will lost saturation after encocded, any idea how to solve this ?

**Comment by disintegration** [comment]
Hi,

I've never seen the brightness/saturation decrease of images after processing with Go. Could you provide your test images / code example demonstrating the issue?

**Comment by kiwionly** [comment]
hi, here the code and sample image

```
package main

import (
	"os"
	"image/jpeg"
)

func main() {

	reader, err := os.Open("berry.jpg")

	if err != nil {
		panic(err.Error())
	}

	im, err := jpeg.Decode(reader)

	if err != nil {
		panic(err.Error())
	}

	out, err := os.Create("out.jpg")

	if err != nil {
		panic(err.Error())
	}

	jpeg.Encode(out, im, &jpeg.Options{
		100,
	})
}
```
after encode, switch the image back and fore to compare, you will see the saturation is lost, the output is darker while original is more dynamic red color.

![berry](https://user-images.githubusercontent.com/174617/36404089-c64c4b1a-1623-11e8-9373-4f83fb874496.jpg)

**Comment by kiwionly** [comment]
I had a result look like this after encode from my PC.

![5d40897cde3b2875e0a5d0f33f95dcfa71956c0b](https://user-images.githubusercontent.com/174617/36404140-07ec3c6a-1624-11e8-8f6c-17b20599e971.jpg)

**Comment by kiwionly** [comment]
here the compare from the [site](https://www.diffchecker.com/image-diff)

![download](https://user-images.githubusercontent.com/174617/36404614-aba03508-1626-11e8-9dba-361f83a6dada.png)

**Comment by disintegration** [comment]
Thank you for the example,

The given image has Adobe RGB color profile embedded (for example, the GIMP explicitly states so when opening this image). Most images on the web have sRGB color profile. I think that the `image/jpeg` package doesn't convert the colors to sRGB color space during decoding (which is the default for images without an embedded profile) so the image has dull colors after saving (even when saved as png).

You can try opening an issue in the golang repo.

**Comment by kiwionly** [comment]
Seem like not all images is effected when encode.

I had open an [Issue ](https://github.com/golang/go/issues/23936) at golang repo. 

Thanks !
