### ISSUE TITLE
watermark error: paste a transparent png image to a jpeg image.

### ISSUE THREAD

**Issue by AarioAi** [disintegration/imaging#68]
Use imaging.Paste() to paste a transparent watermark.png to a jpeg image. It'll cause black background to the watermark.

![w020180222340452151815](https://user-images.githubusercontent.com/8835297/36541231-36fba59a-1818-11e8-8e22-f6be5aaa8a6c.jpg)
![luexu 2fwiki 2f180222 2f195249849-v1980](https://user-images.githubusercontent.com/8835297/36541256-4c5d811a-1818-11e8-8ea0-52eba0868b15.jpg)

**Comment by disintegration** [comment]
Try using `imaging.Overlay` instead of `imaging.Paste`: https://godoc.org/github.com/disintegration/imaging#Overlay

See also #41

**Comment by disintegration** [comment]
Closing the issue. Feel free to reopen if it didn't work for you.
