### ISSUE TITLE
Extract Format parsing from `Save` method

### ISSUE THREAD

**Issue by hassansin** [disintegration/imaging#69]
My use case: 
1. Read the image from file/http
2. Resize image.
3. Instead of saving the resized image in a file, send the image buffer to S3.

Right now, I'm using `imaging.Encode()` method. But to get the format, I had to copy format parsing code from `imaging.Save()` method. Can we extract the format parsing into a separate public function so that it can be re-used in userland? I can send a PR if you agree.

**Comment by disintegration** [comment]
Do you mean something like `func FormatFromFilename(filename string) (Format, error)`?

**Comment by hassansin** [comment]
Yes, that's right.

**Comment by disintegration** [comment]
Sure, let's add it. Pull request is welcome.
