### ISSUE TITLE
Scaling is not gamma-aware

### ISSUE THREAD

**Issue by ypomortsev** [disintegration/imaging#80]
Thanks for your hard work on this library! Please consider making the scaling gamma-aware. For example, scaling this image down 50%:

![gamma_dalai_lama_gray](https://user-images.githubusercontent.com/857581/46251181-c6411c00-c400-11e8-8a6c-cbd9c8091448.jpg)

produces:

![out](https://user-images.githubusercontent.com/857581/46251173-91cd6000-c400-11e8-83d0-ad1fd175a8ac.png)

but should look like:

![gamma_dalai_lama_gray_good](https://user-images.githubusercontent.com/857581/46251188-e8d33500-c400-11e8-90b6-0da32e932da6.jpg)

This is [the code I used to generate the scaled versions](https://github.com/ypomortsev/imaging-resize).

See Eric Brasseur's [Gamma error in picture scaling](http://www.ericbrasseur.org/gamma.html) for more details.

**Comment by disintegration** [comment]
You are right, the implemented image processing functions do not convert images to/from a linear color space. It was a deliberate decision (at least for v1 of the package). Here are some considerations:

- The `image.Image` type does not provide a color space information and I'm not sure if it's a good idea to assume all images are sRGB.
- Extra convertion steps would make the image manipulation slower (I don't have any benchmarks, though). 
- The `imaging` package produces 8bit/channel images (image.NRGBA) only, which is not suitable to make the colorspace convertion a separate function.

If you really need a more accurate image scaling, consider using the other package I wrote - `github.com/disintegration/gift`. Here's the example:

```go
package main

import (
	"image"
	_ "image/jpeg"
	"image/png"
	"log"
	"os"

	"github.com/disintegration/gift"
)

func main() {
	src, err := loadImage("gamma_dalai_lama_gray.jpg")
	if err != nil {
		log.Fatal(err)
	}

	w, h := src.Bounds().Dx()/2, src.Bounds().Dy()/2

	g := gift.New(
		gift.ColorspaceSRGBToLinear(),
		gift.Resize(w, h, gift.LanczosResampling),
		gift.ColorspaceLinearToSRGB(),
	)
	dst := image.NewRGBA(g.Bounds(src.Bounds()))
	g.Draw(dst, src)

	err = saveImage("out.png", dst)
	if err != nil {
		log.Fatal(err)
	}
}

func loadImage(filename string) (image.Image, error) {
	file, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	img, _, err := image.Decode(file)
	if err != nil {
		return nil, err
	}
	return img, nil
}

func saveImage(filename string, img image.Image) error {
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()
	if err := png.Encode(file, img); err != nil {
		return err
	}
	return nil
}
```

![gamma_dalai_lama_gray](https://user-images.githubusercontent.com/2706839/46251607-ccb2b080-c45f-11e8-8a3f-9096f3b9786f.jpg)
![out](https://user-images.githubusercontent.com/2706839/46251609-cf150a80-c45f-11e8-9683-775ff54d6222.png)

**Comment by ypomortsev** [comment]
Very cool, thanks for the thorough answer. I'll check out gift.
