### ISSUE TITLE
Open Base64

### ISSUE THREAD

**Issue by LoganArnett** [disintegration/imaging#85]
Am I able to use the `Open` method on a base64 string directly instead of a file? I am trying to use this in an AWS Lambda and trying to see if I can avoid even creating temporary files

**Comment by disintegration** [comment]
If you have a base64-encoded image data as a string, you can use `Decode` instead. e.g.:

```go
img, err := imaging.Decode(base64.NewDecoder(base64.StdEncoding, strings.NewReader(data)))
```

**Comment by LoganArnett** [comment]
Wow, yep, totally overlooked that, thanks @disintegration my bad

Awesome go package by the way 👍
