### ISSUE TITLE
Fading an image programmatically 

### ISSUE THREAD

**Issue by ksred** [disintegration/imaging#88]
Hi there

I would like to use this library to programatically fade an image. The idea is to have an image fade in from one corner to another, or from the centre out. I'd like to do this programatically if possible, instead of overlaying an already faded image.

Could you suggest a way to implement this? Is this something this is capable of currently?

Thanks for the great library!

**Comment by disintegration** [comment]
Hi, 

There is no predefined function for "fade in" effect in `imaging`. You can try using a `Clone` function to convert an image to NRGBA type and manipulate its pixels using `NRGBAAt` and `SetNRGBA` methods (e.g. change an alpha channel or rgb channels depending on the pixel coordinates).

Here's a small example:

```
package main

import (
	"image"
	"log"

	"github.com/disintegration/imaging"
)

func main() {
	img, err := imaging.Open("branches.jpg")
	if err != nil {
		log.Fatal(err)
	}

	img = fadeIn(img)

	err = imaging.Save(img, "out.png")
	if err != nil {
		log.Fatal(err)
	}
}

func fadeIn(src image.Image) image.Image {
	dst := imaging.Clone(src)
	b := dst.Bounds()
	for y := b.Min.Y; y < b.Max.Y; y++ {
		m := float64(y-b.Min.Y) / float64(b.Dy())
		for x := b.Min.X; x < b.Max.X; x++ {
			c := dst.NRGBAAt(x, y)
			c.A = uint8(float64(c.A) * m)
			dst.SetNRGBA(x, y, c)
		}
	}
	return dst
}
```

![out](https://user-images.githubusercontent.com/2706839/52977892-218b9f00-33e0-11e9-9510-82be291afbe6.png)

**Comment by ksred** [comment]
Awesome, thanks!
