### ISSUE TITLE
 imaging.Open with bytes

### ISSUE THREAD

**Issue by jeffotoni** [disintegration/imaging#89]
Hello guys,
Not able to do an imaging.Open getting bytes from the file instead of the path?
To apply everything in memory?

imaging.Open (file_bytes?

**Comment by disintegration** [comment]
Hi,

Most probably you are looking for `imaging.Decode`: https://godoc.org/github.com/disintegration/imaging#Decode

It takes an `io.Reader` instead of a filename as a first argument.

**Comment by jeffotoni** [comment]
**Perfect**, just this, now I need to do Resize:

dstImage: = imaging.Resize (srcImage, width, height, imaging.Lanczos)

Instead of imaging.Save (dstImage, "/tmp/t.png") on disk, I need bytes in memory, I do not want to save to disk.

How can I proceed?

Thank you

**Comment by disintegration** [comment]
See: https://godoc.org/github.com/disintegration/imaging#Encode

**Comment by jeffotoni** [comment]
Excellent Very Good.
Exactly that.
Just had to define my io.Write as a new buffer
buf2: = bytes.NewBuffer (nil)

Thank you guys.

Very good, I do not need to save anything on disk.

**Comment by joshhornby** [comment]
@jeffotoni Do you happen to have a fully working example of this in action?

Thanks in advance.

**Comment by disintegration** [comment]
Here's the example of encoding to / decoding from a slice of bytes:

```go
package main

import (
	"bytes"
	"image/color"
	"log"

	"github.com/disintegration/imaging"
)

func main() {
	// Create a new image.
	origImage := imaging.New(100, 100, color.NRGBA{255, 0, 0, 255})
	log.Printf("original image bounds: %v", origImage.Bounds())

	// Encode the image into a byte slice as PNG.
	var buf bytes.Buffer
	err := imaging.Encode(&buf, origImage, imaging.PNG)
	if err != nil {
		log.Fatal(err)
	}
	pngBytes := buf.Bytes()
	log.Printf("encoded PNG image size: %d bytes", len(pngBytes))

	// Decode image back from the byte slice.
	decodedImage, err := imaging.Decode(bytes.NewReader(pngBytes))
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("decoded image bounds: %v", decodedImage.Bounds())
}
```

```
2019/03/29 23:29:47 original image bounds: (0,0)-(100,100)
2019/03/29 23:29:47 encoded PNG image size: 292 bytes
2019/03/29 23:29:47 decoded image bounds: (0,0)-(100,100)
```
