### ISSUE TITLE
Clarify difference between imaging and gift in README

### ISSUE THREAD

**Issue by danielparks** [disintegration/imaging#92]
I know there was an explanation in https://github.com/disintegration/imaging/issues/17, but it would be really helpful if that information were in the README for both `gift` and `imaging`.

The confusion stems from these two packages being written by the same person. They cover roughly the same ground, but they're completely independent — neither depends on the other. For example, if `imaging` depending on `gift`, it would be more obvious what was going on.

Perhaps something like:

> ### `imaging` versus `gift`
> 
> [`imaging`](https://github.com/disintegration/imaging) is designed to be a lightweight and simple image manipulation package. It consistently returns `*image.NRGBA`.
> 
> [`gift`](https://github.com/disintegration/gift) supports more advanced image processing such as convolution filters, color adjustments, and color space conversions. It is designed to support different output image types, and to provide easy-to-use API for chaining processing steps together.

**Comment by disintegration** [comment]
Sure, will do that.

It probably makes sense to add a FAQ section to the README and put it in there, along with some other questions that was asked several times. One example being the correct way of EXIF orientation handling.

**Comment by disintegration** [comment]
Done https://github.com/disintegration/imaging/commit/465faf0892b5c7b3325643b0e47282e1331672e7
