### ISSUE TITLE
Rotate180 is not worked as expect

### ISSUE THREAD

**Issue by messyidea** [disintegration/imaging#95]
[rotate.zip](https://github.com/disintegration/imaging/files/3094543/rotate.zip)

Hi, you can try to use this code, the image was rotate 90 when use Rotate180 function

**Comment by disintegration** [comment]
Hi, 

Most probably, the image contains the EXIF orientation tag. Try opening it with the `AutoOrientation` option (https://godoc.org/github.com/disintegration/imaging#AutoOrientation), e.g.:

```
src, err := imaging.Open("test.jpg", imaging.AutoOrientation(true))
```

**Comment by messyidea** [comment]
It's okey now, thanks
