### ISSUE TITLE
Image convert and webp

### ISSUE THREAD

**Issue by pyprism** [disintegration/imaging#97]
Is to possible to convert from jpeg/png to webp using this library ?

**Comment by disintegration** [comment]
Imaging package does not support encoding webp images directly using its `Save` function, so you need to import another package for this task. I've found the `github.com/chai2010/webp` package using the godoc.org search, that encodes webp images. I don't have any experience with it, so cannot recommend, but here's the code that at least works for me. Hope it helps.

```
package main

import (
	"log"
	"os"

	"github.com/chai2010/webp"
	"github.com/disintegration/imaging"
)

func main() {
	img, err := imaging.Open("test.jpg", imaging.AutoOrientation(true))
	if err != nil {
		log.Fatal(err)
	}
	file, err := os.Create("test.webp")
	if err != nil {
		log.Fatal(err)
	}
	if err := webp.Encode(file, img, nil); err != nil {
		log.Fatal(err)
	}
	if err := file.Close(); err != nil {
		log.Fatal(err)
	}
}
```
