### ISSUE TITLE
What's the difference between thumbnail and fill?

### ISSUE THREAD

**Issue by danqing** [disintegration/imaging#99]
Thanks for the great library!

I wonder what's the difference between fill and thumbnail? Both seem to resize and crop the image to fill a space; am I missing something here?

**Comment by disintegration** [comment]
The difference between these two functions is that `Fill` allows the caller to pass the `anchor` parameter while the `Thumbnail` always uses the `Center` anchor point.

`Thumbnail`  was implemented first, `Fill` was added to the later. `Thumbnail` now uses `Fill` under the hood:

```
func Thumbnail(img image.Image, width, height int, filter ResampleFilter) *image.NRGBA {
	return Fill(img, width, height, Center, filter)
}
```

**Comment by danqing** [comment]
Thanks for the explanation!
